[project]
name = "fgo-gnss-integrity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.6.0",
    "numpy>=2.3.3",
]
